services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: [ "php", "-S", "0.0.0.0:8000" ]

