services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    working_dir: /app
    tty: true
    stdin_open: true
    command: [ "php", "-S", "0.0.0.0:8000" ]

